spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'whereismyteamcontact@gmail.com'
    password: '#team2022'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl.enable: false

