server:
  port: 8080

spring:
  application:
    name: dev

  datasource:
    url: jdbc:mysql://whereismyteamdb.cjr7wntaenbp.ap-northeast-2.rds.amazonaws.com:3306/whereismyteamDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username:  admin
    password:  '#team2022'
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전

  jpa:
    show-sql: true
    generate-ddl: true
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true


